### ISSUE TITLE
Modify bar labels in Go Term vs Gene Count

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-go-term-visualizer#10]
Right now the `populationAnnotationCount` is shown, although the Y-axis is the number of genes (matches).

Could we show the number of genes in the label, and instead have the percentage of the matches in the `populationAnnotationCount` in parentheses?

As an example, if we have a GO-term with 5 matches and 82 populationAnnotationCount, the label for that bar should be:

> 5 (6.1%)

**Comment by rachellyne** [comment]
Yes that looks good.  Or we could have a toggle for the Y-axis between actual number and proportion?  If we show proportion we could add another bar next to each bar for the proportion in the background population.

**Comment by akshatbhargava123** [comment]
We see that now on hover of bars like this:
![image](https://user-images.githubusercontent.com/22184427/63181399-87926f80-c06d-11e9-84ee-09b4acb0ef3e.png)

`populationAnnotationCount` can be seen on top of bars and matches can be seen on y-axis as before.

**Comment by heralden** [comment]
Sorry if I was unclear. By label I mean the text on top of the bars. 

So basically move the amount of matches with the percentage in parentheses, that is now in the on-hover tooltip to be the label for the bars instead.

We also need some more space to the top as the labels get cropped. If you want to test with this list, it's called `PL FlyTF_REDfly_TFs` and part of flymine.

![2019-08-19-095335_1033x526_scrot](https://user-images.githubusercontent.com/3865590/63253227-567e8e80-c269-11e9-81cf-c840404b19b4.png)
