### ISSUE TITLE
Improve the display on bluegenes-GO-term-visualizer

### ISSUE THREAD

**Issue by egbobright** [intermine/bluegenes-go-term-visualizer#18]
I will like to work on the blue-genes-GO-term-visualizer CSS display. 
1. It will look better if the box is centralized rather than it being on the far left. 
2.Also the input field for the RESULT LENGTH is too long considering it just accepts two digit numbers

Please can I work on them?

![bluegenes](https://user-images.githubusercontent.com/45522273/76696312-36da0800-668a-11ea-8e13-70250ff795cd.PNG)

**Comment by heralden** [comment]
I think that's a great idea. The filter panel could definitely be made more compact.
Try giving it a new look and we'll see whether we prefer it when you create the PR.

**Comment by egbobright** [comment]
Good morning,

I'm done with the contribution but running 'git push -u origin
<branchname>' (for me my branch name is dev) produced showed the test
failing, the error message is attached.

Thank you.

**Comment by egbobright** [comment]
Hello,

I modified the filter panel as suggested. I've sent a new commit on issue
#19. While I think your suggestion on making it more compatible is perfect,
I also think leaving out the h4 header and making the apply filter button
inline with the p, selection and input tag will not be a great idea.

Kindly check my commit and let me know.

Thank you.

**Comment by heralden** [comment]
Fixed with #19
