### ISSUE TITLE
Not working in BlueGenes deployment: keeps loading

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/bluegenes-go-term-visualizer#2]
It looks like the visualizer is not working, it keeps loading. See example: http://bluegenes.apps.intermine.org/#/reportpage/humanmine/Gene/6087400

**Comment by akshatbhargava123** [comment]
So I checked it, added error handling to it but it doesn't work in deployment. It can only mean that we're not getting passed the right params. Just to confirm @yochannah, does BlueGenes pass the list id for this visualizer?

`dataToInitialiseToolWith = {
					"class" : "Gene",
					"format" : "list",
					"value" : "PL_obesityMonogen_ORahilly09"
				}`

It should look something like above.

**Comment by heralden** [comment]
As I mentioned in the chat, this tool is for the list page, which BlueGenes currently don't support tools for yet.

I created an issue and I'll look into adding this sometime this week or the next.
https://github.com/intermine/bluegenes/issues/376

I'll be busy working on something else for a while, but let me know if it's important that this gets fixed quickly, in which case I can prioritize it.

**Comment by heralden** [comment]
I have implemented this in https://github.com/intermine/bluegenes/pull/378 and *bluegenes-GO-term-visualizer* is working. Well done!

![2019-07-22-135700_937x1026_scrot](https://user-images.githubusercontent.com/3865590/61636938-93695c80-ac8e-11e9-97bc-0e4637a29aa2.png)

Sadly you'll only be able to test this yourself by running a local bluegenes instance, with that branch checked out. (Or ask me to test it.)
We haven't deployed an updated bluegenes in ages, but we're looking to do it once Yo's back next week.

I'll close this issue now.
