### ISSUE TITLE
Display GO term instead of GO:XXX code

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-go-term-visualizer#8]
I hope it won't look too bad with the long names if the text is smaller and they're spread over two lines. You'll need to truncate the longer ones (perhaps a limit of 25 characters is reasonable?), so you should experiment with that.

Probably still a good idea to display the GO:XXX code on hover though, if it's easy to implement.

**Comment by akshatbhargava123** [comment]
@uosl , just to make sure, this issue mean converting GO:XXX code to XXX only in the charts, right?

**Comment by heralden** [comment]
@akshatbhargava123 Sorry, I might not have been clear in my description.

What I mean is to display the name of the GO term, eg. `membrane depolarization during action potential` instead of `GO:0086010`. And yes, only doing this visually in the charts.

**Comment by akshatbhargava123** [comment]
Done, the `name` is truncated on x-axis labels and is shown fully when hovered on bar, the `code` is shown in the the tooltip just in case required. Screenshot:

![image](https://user-images.githubusercontent.com/22184427/63181609-0b4c5c00-c06e-11e9-9839-17a0464ba79a.png)
